"use strict";
exports.__esModule = true;
var reactangle_1 = require("./reactangle");
var circle_1 = require("./circle");
var objCircle = new circle_1.Circle(2);
objCircle.Myarea();
objCircle.display();
var objRect = new reactangle_1.Reactangle(2, 3);
objRect.Myarea();
objRect.display();
